import turtle

wn = turtle.Screen()
wn.bgcolor("black")

# Turtle Set Up
raph = turtle.Turtle()
raph.color("red")
raph.shape("turtle")
raph.penup()

# DRAW turtle shell
raph.left(90)
raph.forward(300)

def draw_octogon(size, color):
    raph.pendown()
    raph.color(color)
    raph.left(90)
    raph.forward(size)  
    raph.left(50)
    raph.forward(size + 90)   
    raph.left(40)
    raph.forward(size + 120)  
    raph.left(40)
    raph.forward(size + 90)  
    raph.left(50)
    raph.forward(size + 100)
    raph.left(50)
    raph.forward(size + 90)
    raph.left(40)
    raph.forward(size + 120)
    raph.left(40)
    raph.forward(size + 90)
    raph.left(50)
    raph.forward(size)
    raph.penup()
   

draw_octogon(100, "green")

raph.goto(-20,230)
raph.setheading(90)
draw_octogon(50, "green")

raph.pendown()
raph.left(40)
raph.forward(70)
raph.left(60)
raph.forward(100)
raph.right(70)
raph.forward(50)
raph.left(70)
raph.forward(100)
raph.right(60)
raph.forward(100)
raph.right(150)
raph.forward(70)
raph.left(30)
raph.forward(120)
raph.right(80)
raph.forward(60)
raph.left(80)
raph.forward(110)
raph.right(80)
raph.forward(50)
raph.penup()

# Draw TMNT
raph.left(150)
raph.goto(-300,300)

raph.pendown()
def draw_T(color):
    raph.color(color)
    raph.right(170)
    raph.forward(100)
    raph.right(90)
    raph.forward(30)
    raph.right(90)
    raph.forward(50)
    raph.left(90)
    raph.forward(100)
    raph.right(90)
    raph.forward(20)
    raph.right(90)
    raph.forward(100)
    raph.left(90)
    raph.forward(50)
    raph.right(90)
    raph.forward(30)
    raph.right(90)
    raph.forward(50)

draw_T("blue")

raph.penup()
raph.goto(300,300)

raph.pendown()
def draw_M(color):
    raph.color(color)
    raph.right(80)
    raph.forward(130)
    raph.right(90)
    raph.forward(20)
    raph.right(80)
    raph.forward(80)
    raph.left(150)
    raph.forward(50)
    raph.right(150)
    raph.forward(50)
    raph.left(140)
    raph.forward(80)
    raph.right(90)
    raph.forward(30)
    raph.right(80)
    raph.forward(130)
    raph.right(90)
    raph.forward(40)
    raph.right(70)
    raph.forward(50)
    raph.left(150)
    raph.forward(50)
    raph.right(50)
    raph.forward(20)


draw_M("orange")
raph.right(150)
raph.penup()
raph.goto(-300,-300)

raph.pendown()
def draw_N(color):
    raph.color(color)
    raph.right(140)
    raph.forward(120)
    raph.right(90)
    raph.forward(20)
    raph.right(70)
    raph.forward(110)
    raph.left(160)
    raph.forward(100)
    raph.right(90)
    raph.forward(20)
    raph.right(90)
    raph.forward(120)
    raph.right(90)
    raph.forward(30)
    raph.right(70)
    raph.forward(80)
    raph.left(160)
    raph.forward(80)
    raph.right(90)
    raph.forward(20)
    
  
draw_N("purple")
raph.penup()
raph.right(190)
raph.goto(200,-180)

raph.pendown()
raph.right(180)
draw_T("red")
wn.exitonclick()